name: Docs Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      with:
        uses: actions/setup-node@v4
        node_version: '20.x'
        cache: 'npm'
    - run: npm i
    - run: npm run build
